= The Battle of Five Armies
:page-role: experimental

[IMPORTANT]
====
*This scenario is from _The Battle of Five Armies_, a Hobbit-themed edition of _Warmaster_. Rules and unit statistics have not been adjusted for _Warmaster Revolution_.*
====

[.page=66]
== The Armies

It is true that the Battle of Five Armies features five armies, but
these fight as two quite separate alliances: the Good side and the
Evil side. For our purposes, it is therefore reasonable to think of
two armies. This page provides all the basic game details and
special rules for the Good and Evil armies.

[.page=66]
=== The Good Army

_The Good side features Elves, Dwarves and Men together wit htheir allies, the Eagles and Beorn._

The *Elves* live to the west of
the Lonely Mountain in the
great forest of Mirkwood. At
the heard of their woodland
realm is a city of caves where
the Elfking holds count. This
is where Thorin and the other Dwarves were imprisoned after
they were captured by the Elves and from where Bilbo
subsequently rescued them. The Elves are brave, strong warriors
and excellent, keen-sighted archers. They form the largest single
contingent in the Battle of Five Armies fighting from the great
southern spur of the mountain to the west of Dale.

The *Dwarves* live to the east
of the Lonely Mountain in the
Iron Hills, an underground
realm ruled by Dáin – Thorin’s
cousin. The Dwarves marched
quickly westwards to the Lonely Mountains when they received
Thorin’s call for help sent via the ravens. Dwarves are short,
stout, broad-shouldered, and tremendously resilient folk who
make stubborn and unyielding warriors. They wear iron armour,
iron shod boots, iron helms and carry massive two-handed
mattocks – heavy, transverse-bladed axes. They are the most
powerful warriors on the Good side and they fight from the
eastern spur of the Lonely Mountain alongside the Men.

The *Men* live to the sound of
the Lonely Mountain by the
shores of Lake Esgaroth in a
town built upon wooden piles
sunk into the water and
consequently known as Laketown. In ages past, their ancestors
lived in the town of Dale, the ruins of which still lie before the
gates of the Lonely Mountain. When Smaug attacked and
destroyed Laketown, it was Bard who shot the Dragon and who
subsequently led a force of Men to the Lonely Mountain to find
the long lost treasure. Neither as accurate marksmen as Elves nor
as powerful combatants as Dwarves, Men are nonetheless brave
and competent warriors. At the Battle of Five Armies they
fight alongside the Dwarves upon the eastern spur.

The great *Eagles* are
intelligent and noble
creatures. By the time of
the Battle of Five Armies
they have already
encountered Thorin and his
companions and rescued
them from Wargs by
carrying them to their high
eyries. Their speed and
incomparable eyesight enables them to track the army of Bolg
and eventually to come to the rescue of the Good army, toppling
the Goblins from the mountain crags above the Good forces.

*Beorn* is a chiftain of the
wilds, but he is also a
shapeshufter able to transform
into a huge bear. It is in the
shape of a monstrous bear that
he joins the Battle of Five
Armies in its final stages,
battering his way through the
bodyguard of Bolg before slaying the Goblin leader to end the
battle.

*Gandalf the Grey* is a wizard of
incalculable age and immeasurable
wisdom. He takes command at the Battle
of Five Armies, organising the council of
war and directing the forces before the
Goblin assault.

*The Elfking* – Lord of all the Elves of Mirkwood and a just if
stern ruler.

*Dáin* is the Lord of the Iron Hills – the leader of the Dwarf army
and cousin to Thorin. Like all Dwarves he is proud, stubborn,
hates Goblins and isn’t too found of Elves either.

*Bard* is the leader of the Men of Laketown and slayer of Smaug
the Dragon. Grim in manner and intolerant of fools he is brave,
honest, and fair.

[%header,format=tsv,role=unit,cols="2*<,7*^,^a",frame=none,grid=rows]
|===
include::partial$bo5a-scenario-good.tsv[]
|===

[.page=67]
[#scenario-good-special-rules]
== Special rules

[[elves,†1]]1. Elves:: Elves have incredibly quick reactions making them exceptionally potent warriors. To represent this, Elves add +1 to their dice
when rolling Attacks for shooting and in the first round of each combat engagement. Note that this bonus applies in the first
round of each combat including combats resulting from an advance. It does not apply during subsequent rounds.

[[eagles,†2]]2. Eagles:: Eagles can fly.

[[beorn,†3]]3. Beorn:: Beorn causes terror in his enemies.

[[gandalf,†4]]4. Gandalf:: Gandalf is both Wizard and General – he can issue commands to any units on the Good side. Note that his Attacks and
Command value already include the extra +1 General’s bonus.

[[elfking,†5]]5. The Elfking:: The Elfking is Lord of the Elves. Because of the animosity between the Elfking and Dwarves, the Elfking cannot issue orders
to a unit of Dwarves, nor can he issue a brigade order to a group of units than includes a unit of Dwarves.

[[dain,†6]]6. Dáin:: Dáin is the Lord of the dwarves of the Iron Hills. Because of teh animosity between theElfking and the Dwarves, Dáin cannot
issue orders to a unit of Elves, nor can he issue a brigade order to a group that includes Elves.

[[bard,†7]]7. Bard:: Bard is the slayer of Smaug and a famous archer – note that he has a single combat attack and a single shooting bonus attack
indicated by his Attack values.  He can add this shooting attack to any unit he is with, not just to bowmen.

[[thorin,†8]]8. Thorin:: Thorin is not allowed to give any orders until the wall is broken as described in the special rules for the Battle of Five Armies
scenario. Once the wall is broken he can give orders to any units, even to Elves. However, Thorin can only give orders to a unit
he is touching – unlike other a characters he has no command range. This makes him a limited commander but a tremendously
useful fighter as he adds +3 Attacks to a unit he has joined.

[.page=68]
=== The Evil Army

_The Evil side features Goblins, Goblin Wolf Riders and Wargs._

*Goblins* are stunted, mean-minded,
cruel and numerous
creatures whose lairs infest
the north of the world and the
great mountain chains such
as the Misty Mountains.
They mostly live beneath the
earth as they detest sunlight, and when they move above ground
they shamans create clouds of darkness to shelter them from the
sun. On the whole, they prefer to go about their evil at night or
under the shade of dark forests. They hate Elves, Men and
Dwarves but also each other, for they are bitter creatures full of
mischief, resentment and self-loathing.

Goblins fight in great disorganised hoards made up of creatures
of all shapes and sizes, armed with curved scimitars, bows,
spears, clubs, etc. They are ill disciplined but savage and take
great delight in surrounding and destroying less numerous and
helpless enemies. They are not bold or especially powerful
warriors but their numbers make them dangerous. They masters
care little whether they live or die, and are prepared to throw
away hundreds of Goblins warriors just to wear down the enemy.

Goblins are accompanied
by huge and dangerous
wolves called *Wargs*.
These are especially large
and unusually intelligent creatures who have made
common cause wit the Goblins. The two races share many
things including a test for man-flesh. Wargs live in the wilds
around and adjoining the Goblin lairs from where they gather
information that they pass on to the Goblin leaders.

Some Goblins even ride
Wards into battle – though it
is an especially foolhardy
and daring Goblin that will
hand onto a Warg’s back as
it leaps onto its foes biting
throats and goring flesh.
These *Wolf Riders* form an important part of the Evil forces.

*Bolg*, son of Azog, is the leader of the Evil army and the greatest
of all the other chieftains of the Goblins in the north of the world.
His father was slain by the Dwarves in a great battle to the south
of the Misty Mountains, after which he united all the Goblin
tribes under his leadership.

*Shamans* represent the unnamed shamans that accompany the
Goblin horde, summoning and controlling the great swarms of
darkness that swirl about the battlefield.

*Chieftains* represent the unnamed subordinates of Bolg in the
great Goblin horde.

[%header,format=tsv,role=unit,cols="2*<,7*^,^a",frame=none,grid=rows]
|===
include::partial$bo5a-scenario-evil.tsv[]
|===

[.page=68]
[#scenario-good-special-rules]
== Special rules

[[goblins,†1]]1. Goblins:: Goblin infantry and cavalry units fight with a variety of weapons including some bows and thrown weapons such as spears and
axes. To represent this, Goblins and Wolf Rider units are allowed to shoot as if they had bows but their range is reduced to 15cm.

[[wolf-riders,†]]2. Wolf Riders:: Wolf Riders fight in a swirling mass that is highly mobile if rather ineffective when it comes to close quarter fighting.  To
represent this extraordinary manoeuvrability, a Wolf Rider stand is assumed to be able to see all the way round – not just to its
front as are other stands. This enables Wolf Riders to shoot in any direction, or to charge or evade from the closest enemy within 20cm regardless of their relative position.

[[bolg,†3]]3. Bolg:: Bolg is the army’s General. One unit of Goblins in the army can be nominated as Bolg’s bodyguards – this unit must be
identified in some way so that it is easily recognised. If Bolg is fighting with his bodyguard then his Attack bonus is doubled
from +2 to +4.

_Although the total value of the Good side is greater than the Evil side, the Evil side also has the Ambush whilst
the Eagles and Beorn and not available to the Good player at the onset and may not necessarily arrive until the
battle is over. In fact, the Evil side has 600 points of troops available whilst the Good side has only 485 points of
troops deployed at the start, plus the advantage of position._

== The Battlefield

The battle takes place in the Valley of Dale that lies between two
spurs of the Lonely Mountain. The mountain is represented by
the northern edge of the table and is impassable. This is referred
to as the ‘mountainous edge’.

The entrance to the Dwarf Halls beneath the mountain lie at the
point marked Thorin’s gate on the map – use the longer of the
ruinous Citadel wall sections to represent this.

The two mountain spurs are represent by the Citadel plastic
hill pieces. Each spur has a low hill slope and an impassable
rocky cliff. The Good forces deploy on the lower slopes.

Thorin and his companions have blocked the River Running
where it springs from the mountain creating a deep pool between
Thorin’s Gate and the eastern spur. This is represented by one of the
card strips and can be adjusted to size to suit the table width
by placing the spur section over the card. The pool is impassable.

The course of the River Running is shown on the map. Use the
card river sections to represent this. The river is impassable
except at the ford as shown. Note that the ford is 6cm wide and
can be crossed as open ground. This i the only way to cross the
river (apart from the Eagles, which can fly across of course).

The ruins of the old town of Dale lie along the southern edge of
the battlefield along the western river bank. Use the plastic
Citadel ruin sections to demark the area as shown on the map–
this counts as xref:rules:movement.adoc#broken-ground[broken ground].

image::five-armies/battlefield.svg[width=1428,height=1770,role=column-span]

_*A note on map layout:* If your table is not as wide as the dimensions given above, reduce the
width of the pool to compensate. If your table is too short, reduced the
South part of the map._

== Deployment

All the Elven units must be set up on the Western Spur within the
Elven deployment zone together with the Elfking and Gandalf.
The Dwarf units, Men, Dáin and Bard must be set up on the
Eastern Spur within the Dwarf/Men deployment zone. Thorin
must be placed behind Thorin’s Gate. All the Good army is
deployed at the start of the game apart from the Eagles and
Beorn.

The Evil army enters the game during the first turn – no Evil
models are placed on the battlefield at the start of the game.

=== Evil Cavalry deployment

The Evil side automatically has the first turn in this battle. In the
first Evil turn, the Evil player must place all Wolf Rider and
Warg units plus one Goblin Chieftain at the eastern edge of the
tabletop along the line marked ’Evil Cavalry’.

Once positioned, any Evil units can be given orders, move,
shoot, and fight combat that turn as usual.

=== Evil Infantry deployment

Following the first turn, evil units are deployed according to the
roll of a dice. This represents the somewhat uncoordinated
advance of the huge Evil horde into the valley. From the second
turn onwards, the player rolls a dice at the start of the Evil side’s
turn. The player places the number of Goblin units indicated plus
any one character that he wishes. These are all positioned at the
edge of the tabletop along the line marked ‘Evil Infantry’.

Once positioned, any Evil units can move, shoot and fight
combat that turn.

Evil units continue to be placed at the start of each Evil turn until
all the units have been committed to battle. If there are any
characters remaining to be deployed once the final unit is placed
on the table then these must be deployed as well. Note that a dice
roll greater than the number of remaining units means that all the
units are placed – it is not necessary to roll an exact number.

=== The Evil ambush

Bolg, the Goblin commander, has cunningly sent a small group
of Goblins to scale the mountainside and drop rocks from the
heights onto the Good forces below. These ambushing forces are
not represented by models – instead we use a dice roll to
determine the effect of the ambush.

The ambush is automatically activated once the entire Goblin
army has been deployed. This indicates the the ambushers have
scaled the heights and can start to throw rocks onto Good units
position on the spurs beneath them. The Evil player resolves
the ambush as three shooting attacks during the Shooting phase.
Each turn the Evil player selects one Good unit on each spur –
any unit that is wholly or partially on a spur can be selected but
only one unit per spur. Calculate casualties as you would for
three normal shooting attacks. For purposes of working out drive
backs, the ambushers are assumed to be at the point on the
mountain table edge closest to the target unit.

Note that ambushers are positioned above the Good units – so
their targets do not count as defended but as in the open (i.e. 4+
to hit).

=== Deploying the Eagles & Beorn

Neither the Eagles nor Beorn can attempt to join the battle until all
the Evil army has been deployed. Once the entire Evil army has
deployed, the Eagles and Beorn and potentially deployed at the
start of any Good turn according to the roll of a dice.

At the start of his turn, the Good player rolls a dice.  If the Good
force has lost any entire units then add +1 to the decide roll for each
unit lost. On a 6 (or more) either the Eagles of Beorn can be
placed at any point along the western edge of the table marked
’Eagles/Beorn’ on the map. It will therefore take two successful
scores of a 6 to deploy both units and it is possible that one or
both fail to arrive before the battle is over. Note that there is no
need to deploy the Eagles before Beorn – the player can decide
which to deploy first.

Once positioned, the Eagles/Beorn can be given orders, move,
shoot and fight combat that turn as usual. Note that Beorn is a
monster unit and therefore either requires orders or can move on
initiative if visible enemy are within 20cm – this means it is
important not to place Beorn too far from the Good characters.
The Eagles can home back and can therefore move without
orders if necessary – this is useful for moving them into the thick
of things.

== Special rules

=== Thorin and The Gate

Thorin’s Gate is a wall constructed by Thorin and his Dwarves
in the days before the battle. It completely blocks off the tunnel
entrance to the halls beneath the Lonely Mountain. This wall is
completely impenetrable to all stands including characters and
even flyers (it almost reaches the tunnel’s roof). So long as
Thorin is behind the wall he cannot move or issue orders. The
wall has been constructed in such a way that by activating well-placed
levers the whole wall can be collapsed to allow Thorin to
escape. The Good player can do this by issuing a single order from
Thorin – effectively by rolling 8 or less on 2D6 in the
Command phase. Once the wall is collapsed Thorin can move
normally and can issue orders to Good units as noted under
the rules for Thorin.

=== Eagles and Ambushers

Once the Eagles have been deployed, the Evil ambush ends
automatically. It is assumed that other Eagles have peeled away
from the main formation to dislodge the Goblins from the
heights. Note that this means that the Evil side always gets one
turn to drop rocks before the good side makes its first roll to see
if the Eagles arrive.

== Victory

The battle lasts until one side is forced to withdraw. This happens
once either side has lost half of its units, or if either General is
slain. Note that the withdraw level for the Good side is set on the
original eight units – it does not include the Eagles or Beorn; this
is quite deliberate and makes the game more desperate for the
Good side.

*Good Side:* Withdraw when four units are destroyed or Gandalf
is slain.

*Evil Side:* Withdraw when eight units are destroyed or Bolg is
slain.

Once one side has withdrawn, add up the Victory Points scored
by each side in the xref:rules:end-of-the-battle.adoc#victory-points[usual way]. The side that scores
the greatest value wins the battle. Remember, once one side
withdraws it cannot score greater than its enemy, so the best it
can do is draw.

Once you’ve played the game a few times, we recommend that
players play twice before comparing scores – once in charge of
the Good side and once in charge of the Evil side. This means
that the players’ combined scores can be used to compare
performance when commanding both armies.

== A note on magic items

Magic items have been taken into account by adjusting the
Attack values of the various characters compared to the
<<expanded-army-lists>>. Magic items are not used in the
Battle of Five Armies scenario as described.  However, once
players have mastered the battle they might want to try choosing
from the <<magic-item-list>>. In this case, reduce Gandalf’s and
Thorin’s Attack values by 1 each and allow the Good side to have
up to 50 points of magic items instead.

== Tactical notes

This battle can look very desperate for the Good side –
outnumbered to the front, ambushers behind, and badly needed
reinforcements always a dice roll away. But don’t despair – the
Good side are by far the better troops and are backed up by a lot
of very able characters. Though things may look bleak for
Gandalf and friends, in fact their position is strong – the Evil side
will do well to prise their enemies from the slopes and are likely
to suffer many casualties trying.

=== Gandalf

You have to decide if you’re going to hold out on both sides of
the river of make a dash across the ford and consolidate your
forces. With Gandalf accompanying the Elves, and the units
of Dwarves and Men faced by fast-moving enemy cavalry, this is
far more likely to succeed by moving the Elves to join their
allies. This will usually prove the best option – but you don’t
want the enemy to unit his forces against you – the key to
victory is to keep the enemy divided.

You have lots of hood heroes – use some to issue commands and
some to back-up units in combat. Thorin is spectacular – but
Dáin and the Elfking can make a significant contribution. Don’t
risk Gandalf unless you’re sure of winning, as a dead Gandalf
means game over! Other characters are less vital to you – don’t
be afraid of throwing them in.

It’s impossible to be sure if the Eagles or Beorn will show up –
and sometimes that cry of “…the Eagles are coming!” will ring
a little hollow. Remember you can bring Beorn or the Eagles on
in any order but it is usually more useful to have the Eagles.
These are great for mopping up the odd stands of cavalry that
tend to evade and hide.

=== Bolg

You have numbers on your side but your foes are well positioned
and stubborn. What you do will depend to some extent on how
the first few turns go. With luck you can move close enough to
the ford to prevent the enemy uniting against your cavalry – so
much the better!

The Wolf Riders can do considerable damage by shooting and
this is much safer than combat – combined with the ambush,
shooting can drive the enemy off the spurs and potentially
confuse them.

You only need to destroy four units to win – so pick the softest
targets and hammer them. That means avoid those stubborn
Dwarves if possible!

Make full use of your Shaman to move units up earl in the battle
– once combat begins use his _Foul Frenzy_ and _dark Swarm_ spells
to improve your chances. Don’t forget Bolg’s Bodyguard, as that
double Bolg bonus is the biggest bonus in the game and makes
all the difference.

=== And for the new player…

Don’t worry about getting every rule right – it will take a few
games to learn how things work. The scenario is relatively
complex – there’s a lot to remember and the tactical constraints
presented by the terrain and deployment are significant.

One of the most important things to remember for this game is
that infantry cannot pursue cavalry. This limits the ability of the
Good side to exploit successful combats against the Wolf Riders
and Wargs. Don’t forget also that stationary infantry positioned
uphill of their enemy count as defended and are thus 5+ to hit and
no charge bonuses count against them – it’s a double whammy.
