= Expanded Unit List – Destruction
:page-layout: armylist
:page-role: armylist experimental
:page-toclevels: 1

****
*Experimental rules designed to be used for casual play.*

_Compiled by ntdars, with the much needed help of the WMR community. Version 2.1._

Discussion: https://wmrexperimental.freeforums.net/thread/288/expanded-unit-lists-casual-play[Expanded Unit Lists for casual play].
****

[#army-selector]
== Forces of Destruction

[%header,format=tsv,role=unit,cols="2*<,7*^,^a",frame=none,grid=rows]
|===
include::partial$expanded-unit-list-destruction.tsv[]
|===

[#special-rules]
== Special rules

// Executioners’, benefiting, target’s

// can → may

[[executioners,†1]]1. Executioners:: Executioners’ to-hit rolls of a 6 reduce
their target’s armour save by −1. Therefore, units with
a 4+ armour save will be downgraded to a 5+
armour save, 5+ armour saves will be downgraded to
a 6+ armour save, [.edit]#and units with a 6+ armour save will have no save at all#.
This ability has no effect on
units benefiting from Fortified Terrain.

[[cold-one-chariots,†2]]2. Cold One Chariots:: Any number of Cold One
Knights may be replaced with a unit of Cold One
Chariots. Note that this unit counts towards the Cold
One Knights min/max value.
+
These units are
equipped with the repeating crossbow (see
xref:dark-elves.adoc#crossbowmen-and-dark-riders[Crossbowmen and Dark Riders]).
+
Cold One Chariots
cannot form brigades except with other units of Cold
One Chariots or Cold One Knights and _vice versa_.

[[black-guard,†3]]3. Black Guard:: Black Guard re-roll failed attack rolls
on the first round of combat when they are charged.

[[cygor,†4]]4. Cygor:: The Cygor’s shooting attack uses the
xref:rules:artillery-and-machines.adoc#stone-thrower[Stone Thrower]
rules as described in the Rulebook.

[[pestigors,†5]]5. Pestigors:: One unit of Bestigors per full 1000 points
can be upgraded to Pestigors for 35 points.

[[weapon-teams,†6]]6. Weapon Teams:: Weapon Teams follow the same
rules for xref:empire.adoc#skirmishers[Empire Skirmishers], but may only join
Clanrat units.
+
Weapon Teams have a shooting range
of only 15cm however they can draw line of sight
from all edges of their base for the purpose of
Evading or Shooting, including shooting at charging
enemies. Note, they still need Line of Sight from their
front edge to charge an enemy.
+
Count enemy Armour values as one
worse than normal when shot by a Weapon
Team.
+
A roll of double 1 during shooting
means the weapon has malfunctioned! The
Weapon Team and its parent unit become
Confused.

[[hellpit-abomination,†7]]7. Hellpit Abomination:: Hellpit Abominations are
so aggressive that they cannot be included as
part of a brigade, not even with other Hellpit
Abominations.
+
They cause terror in their
enemies.
+
The Abomination can shoot warpfire
with a range of 20cm and 2 Attacks that are
worked out in the normal way.
+
Once all hits have
been struck for that round, and assuming it has
not been slain, the Hellpit Abomination
automatically regenerates 1 hit that it suffered
that round. A hit that is inflicted and
subsequently regenerated still counts towards
the results for that round.
+
Per 1000 points, you
can either field a Hellpit Abomination or
Doomwheel, but not both.

[[verminlord,†8]]8. Verminlord:: Only Skaven Grey Seers can be
upgraded to become a Verminlord.
+
A unit that
has been joined by a Verminlord causes Terror in
its enemies.

[[blood-knights,†9]]9. Blood Knights:: Blood Knights ignore the
“Undead” special army rule from the Vampire
Counts Army Selector, however they are still
unaffected by the −1 Combat penalty for fighting
terrifying troops.
+
Blood Knights receive +1
Attack in the first round of every combat when
fighting to their front.
+
Blood Knights are
exceptionally rare, so [.edit]#the army may only include
a single unit].

[[varghulf,†10]]10. Varghulf:: Varghulfs never suffer the −1 Attack
modifier due to being flanked in the side or rear.
+
Once all hits have been struck for that round,
and assuming it has not been slain, the Varghulf
automatically regenerates 1 hit that it suffered
that round. A hit that is inflicted and
subsequently regenerated still counts towards
the results for that round.
